#!/bin/bash
pkgs="ros-build-tools                                    
ros-noetic-desktop-full"

failed=()
all_depends=()
not_in_aur=()

get_depends() {
    while IFS= read -r line; do
        if [[ $line == *"makedepends = "* || ($line == *"depends = "* && $line != *"optdepends = "*) ]]; then
        value=$(echo "$line" | awk -F'=' '{gsub(/^[ \t]+|[ \t]+$/, "", $2); print $2}' | tr -d ':')
        pacman -Si $value > /dev/null
        if [ $? -ne 0 ]; then
            depends+=("$value")
            all_depends+=("$value")
        fi
      fi
    done < .SRCINFO 
}

for pkg in $pkgs; do
    echo "------------------$pkg---------------------"
    if [ -d "$pkg" ]; then
        status=0
        if [ ! -f "$pkg/.SRCINFO" ]; then
            echo -e "\e[31m${pkg}: not exist\e[0m"
            not_in_aur+=("$pkg")
        fi
    else
        git clone https://aur.archlinux.org/$pkg.git
        status=$?
    fi

    if [ $status -ne 0 ]; then
        echo -e "\e[31m${pkg}\e[0m"
        failed+=$pkg
        continue
    fi

    cd $pkg
    rm .git .gitignore -rf

    depends=()
    get_depends 

    cp ../lilac.yaml .

    sed -i "s/aur:.*/aur: $pkg/" lilac.yaml

    if [ ${#depends[@]} -ne 0 ]; then
        echo "repo_depends:" >> lilac.yaml
    fi

    for item in "${depends[@]}"; do
      echo "  - $item" >> lilac.yaml 
    done

    cd ..
done

sorted_all_depends=($(printf "%s\n" "${all_depends[@]}" | sort -u))
all_pkgs=()
not_in_pkgs=()
while IFS= read -r line; do
  all_pkgs+=("$line")
done <<< "$pkgs"

for item1 in "${sorted_all_depends[@]}"; do
  found=0
  for item2 in "${all_pkgs[@]}"; do
    if [ "$item1" = "$item2" ]; then
      found=1
      break
    fi
  done

  if [ "$found" -eq 0 ]; then
    not_in_pkgs+=("$item1")
  fi
done

echo "------------------额外依赖包不在添加的aur包中，请添加到上面列表中--------------------"
for item in "${not_in_pkgs[@]}"; do
  echo "$item"
done

echo -e "\n-----------克隆失败-------------\n"
for item in "${failed[@]}"; do
    echo $item
done

echo -e "\n-----------空仓库:-------------\n"
for item in "${not_in_aur[@]}"; do
    echo $item
done
