#!/bin/bash
pkgs="ros-build-tools                                    
python-catkin_pkg                                  
ros-noetic-catkin                                  
ros-noetic-angles                                  
ros-noetic-cmake-modules                           
console-bridge                                     
ros-noetic-class-loader                            
ros-noetic-cpp-common                              
ros-noetic-rostime                                 
ros-noetic-ros-environment                         
python-rospkg                                      
python-rosdistro                                   
python-rosdep                                      
ros-noetic-rospack                                 
ros-noetic-roslib                                  
ros-noetic-rosunit                                 
ros-noetic-roscpp-traits                           
ros-noetic-genmsg                                  
ros-noetic-genpy                                   
ros-noetic-roscpp-serialization                    
ros-noetic-message-runtime                         
ros-noetic-geneus                                  
ros-noetic-gencpp                                  
ros-noetic-gennodejs                               
ros-noetic-genlisp                                 
ros-noetic-message-generation                      
ros-noetic-rosbuild                                
ros-noetic-rosconsole                              
ros-noetic-pluginlib                               
ros-noetic-xmlrpcpp                                
ros-noetic-std-msgs                                
ros-noetic-rosgraph-msgs                           
ros-noetic-roslang                                 
ros-noetic-roscpp                                  
ros-noetic-pluginlib-tutorials                     
ros-noetic-std-srvs                                
ros-noetic-geometry-msgs                           
ros-noetic-turtlesim                               
ros-noetic-actionlib-msgs                          
ros-noetic-rosgraph                                
ros-noetic-rosout                                  
ros-noetic-rosparam                                
ros-noetic-rosclean                                
ros-noetic-rosmaster                               
ros-noetic-roslaunch                               
ros-noetic-rospy                                   
ros-noetic-rostest                                 
ros-noetic-roslz4                                  
ros-noetic-rosbag-storage                          
ros-noetic-topic-tools                             
ros-noetic-rosbag                                  
ros-noetic-rostopic                                
ros-noetic-actionlib                               
ros-noetic-turtle-actionlib                        
ros-noetic-smclib                                  
ros-noetic-bond                                    
ros-noetic-bondcpp                                 
ros-noetic-nodelet                                 
ros-noetic-nodelet-tutorial-math                   
ros-noetic-actionlib-tutorials                     
ros-noetic-common-tutorials                        
ros-noetic-roslint                                 
ros-noetic-xacro                                   
ros-noetic-python-qt-binding                       
ros-noetic-sensor-msgs                             
ros-noetic-joint-state-publisher                   
urdfdom-headers                                    
urdfdom                                            
ros-noetic-message-filters                         
ros-noetic-image-transport                         
ros-noetic-tf2-msgs                                
ros-noetic-tf2                                     
ros-noetic-tf2-py                                  
ros-noetic-tf2-ros                                 
orocos-kdl                                         
orocos-kdl-python                                  
ros-noetic-tf2-geometry-msgs                       
ros-noetic-visualization-msgs                      
ros-noetic-interactive-markers                     
ros-noetic-rosnode                                 
ros-noetic-rosmsg                                  
ros-noetic-rosservice                              
ros-noetic-roswtf                                  
ros-noetic-tf                                      
ros-noetic-laser-geometry                          
ros-noetic-nav-msgs                                
ros-noetic-map-msgs                                
ros-noetic-resource-retriever                      
ros-noetic-tf2-eigen                               
ros-noetic-urdf-parser-plugin                      
ros-noetic-rosconsole-bridge                       
ros-noetic-urdf                                    
ros-noetic-media-export                            
ogre-1.9                                           
ros-noetic-rviz                                    
ros-noetic-tf2-kdl                                 
ros-noetic-kdl-parser                              
ros-noetic-robot-state-publisher                   
ros-noetic-urdf-tutorial                           
ros-noetic-turtle-tf                               
ros-noetic-turtle-tf2                              
ros-noetic-geometry-tutorials                      
ros-noetic-visualization-marker-tutorials          
ros-noetic-librviz-tutorial                        
ros-noetic-rviz-plugin-tutorials                   
ros-noetic-interactive-marker-tutorials            
ros-noetic-rviz-python-tutorial                    
ros-noetic-visualization-tutorials                 
ros-noetic-qt-gui                                  
ros-noetic-rqt-gui                                 
ros-noetic-rqt-gui-py                              
ros-noetic-qt-dotgraph                             
ros-noetic-rqt-graph                               
ros-noetic-rqt-tf-tree                             
ros-noetic-diagnostic-msgs                         
ros-noetic-rqt-runtime-monitor                     
ros-noetic-rqt-py-common                           
ros-noetic-rqt-nav-view                            
ros-noetic-gl-dependency                           
ros-noetic-rqt-pose-view                           
ros-noetic-rqt-robot-steering                      
ros-noetic-rqt-topic                               
ros-noetic-rqt-moveit                              
ros-noetic-rqt-logger-level                        
ros-noetic-rqt-console                             
ros-noetic-qt-gui-py-common                        
ros-noetic-rqt-bag                                 
ros-noetic-rqt-robot-monitor                       
ros-noetic-rqt-robot-dashboard                     
ros-noetic-qt-gui-cpp                              
ros-noetic-rqt-gui-cpp                             
ros-noetic-rqt-rviz                                
ros-noetic-rqt-robot-plugins                       
ros-noetic-bondpy                                  
ros-noetic-bond-core                               
ros-noetic-dynamic-reconfigure                     
ros-noetic-nodelet-topic-tools                     
ros-noetic-nodelet-core                            
ros-noetic-roscpp-core                             
ros-noetic-rosbag-migration-rule                   
ros-noetic-rosmake                                 
ros-noetic-rosboost-cfg                            
ros-noetic-rosbash                                 
ros-noetic-mk                                      
ros-noetic-roscreate                               
ros-noetic-ros                                     
ros-noetic-roslisp                                 
ros-noetic-trajectory-msgs                         
ros-noetic-stereo-msgs                             
ros-noetic-shape-msgs                              
ros-noetic-common-msgs                             
ros-noetic-ros-comm                                
ros-noetic-ros-core                                
ros-noetic-ros-base                                
ros-noetic-qwt-dependency                          
ros-noetic-rqt-plot                                
ros-noetic-rqt-bag-plugins                         
ros-noetic-rqt-launch                              
ros-noetic-rqt-msg                                 
ros-noetic-rqt-action                              
ros-noetic-rqt-top                                 
ros-noetic-rqt-service-caller                      
ros-noetic-rqt-shell                               
ros-noetic-webkit-dependency                       
ros-noetic-rqt-web                                 
ros-noetic-rqt-publisher                           
ros-noetic-rqt-srv                                 
ros-noetic-rqt-dep                                 
ros-noetic-cv-bridge                               
ros-noetic-rqt-image-view                          
ros-noetic-rqt-py-console                          
ros-noetic-rqt-reconfigure                         
ros-noetic-rqt-common-plugins                      
ros-noetic-viz                                     
ros-noetic-filters                                 
ros-noetic-smach-msgs                              
ros-noetic-smach                                   
ros-noetic-smach-ros                               
ros-noetic-executive-smach                         
ros-noetic-diagnostic-updater                      
ros-noetic-diagnostic-analysis                     
ros-noetic-diagnostic-common-diagnostics           
ros-noetic-diagnostic-aggregator                   
ros-noetic-self-test                               
ros-noetic-diagnostics                             
ros-noetic-urdfdom-py                              
ros-noetic-kdl-parser-py                           
ros-noetic-kdl-conversions                         
ros-noetic-tf-conversions                          
ros-noetic-eigen-conversions                       
ros-noetic-geometry                                
ros-noetic-control-msgs                            
ros-noetic-robot                                   
ros-noetic-roscpp-tutorials                        
ros-noetic-rospy-tutorials                         
ros-noetic-ros-tutorials                           
ros-noetic-desktop                                 
ros-noetic-gazebo-msgs                             
libccd                                             
ignition-cmake-2                                   
ignition-tools-1                                   
ignition-utils-1                                   
ignition-math-6                                    
sdformat-9                                         
ignition-msgs-5                                    
ignition-transport-8                               
ignition-common-3                                  
ignition-fuel_tools-4                              
gazebo                                             
ros-noetic-gazebo-dev                              
ros-noetic-gazebo-ros                              
ros-noetic-camera-calibration-parsers              
ros-noetic-camera-info-manager                     
ros-noetic-polled-camera                           
ros-noetic-gazebo-plugins                          
ros-noetic-gazebo-ros-pkgs                         
ros-noetic-stage                                   
ros-noetic-stage-ros                               
ros-noetic-simulators                              
ros-noetic-image-geometry                          
ros-noetic-vision-opencv                           
ros-noetic-pcl-msgs                                
pcl                                                
ros-noetic-pcl-conversions                         
ros-noetic-pcl-ros                                 
ros-noetic-perception-pcl                          
ros-noetic-laser-assembler                         
ros-noetic-laser-filters                           
ros-noetic-laser-pipeline                          
ros-noetic-compressed-depth-image-transport        
ros-noetic-compressed-image-transport              
ros-noetic-theora-image-transport                  
ros-noetic-image-transport-plugins                 
ros-noetic-image-rotate                            
ros-noetic-image-proc                              
ros-noetic-stereo-image-proc                       
ros-noetic-depth-image-proc                        
ros-noetic-image-view                              
ros-noetic-image-publisher                         
ros-noetic-camera-calibration                      
ros-noetic-image-pipeline                          
ros-noetic-image-common                            
ros-noetic-perception                              
ros-noetic-hardware-interface                      
ros-noetic-controller-interface                    
ros-noetic-realtime-tools                          
ros-noetic-forward-command-controller              
ros-noetic-position-controllers                    
ros-noetic-controller-manager-msgs                 
ros-noetic-controller-manager                      
ros-noetic-joint-state-controller                  
ros-noetic-diff-drive-controller                   
ros-noetic-control-toolbox                         
ros-noetic-transmission-interface                  
ros-noetic-joint-limits-interface                  
ros-noetic-gazebo-ros-control                      
ros-noetic-urdf-sim-tutorial                       
ros-noetic-desktop-full"

failed=()
all_depends=()
not_in_aur=()

get_depends() {
    while IFS= read -r line; do
        if [[ $line == *"makedepends = "* || ($line == *"depends = "* && $line != *"optdepends = "*) ]]; then
        value=$(echo "$line" | awk -F'=' '{gsub(/^[ \t]+|[ \t]+$/, "", $2); print $2}' | tr -d ':')
        pacman -Si $value > /dev/null
        if [ $? -ne 0 ]; then
            depends+=("$value")
            all_depends+=("$value")
        fi
      fi
    done < .SRCINFO 
}

for pkg in $pkgs; do
    echo "------------------$pkg---------------------"
    if [ -d "$pkg" ]; then
        status=0
        if [ ! -f "$pkg/.SRCINFO" ]; then
            echo -e "\e[31m${pkg}: not exist\e[0m"
            not_in_aur+=("$pkg")
        fi
    else
        git clone https://aur.archlinux.org/$pkg.git
        status=$?
    fi

    if [ $status -ne 0 ]; then
        echo -e "\e[31m${pkg}\e[0m"
        failed+=$pkg
        continue
    fi

    cd $pkg
    rm .git .gitignore -rf

    depends=()
    get_depends 

    cp ../lilac.yaml .

    sed -i "s/aur:.*/aur: $pkg/" lilac.yaml

    if [ ${#depends[@]} -ne 0 ]; then
        echo "repo_depends:" >> lilac.yaml
    fi

    for item in "${depends[@]}"; do
      echo "  - $item" >> lilac.yaml 
    done

    cd ..
done

sorted_all_depends=($(printf "%s\n" "${all_depends[@]}" | sort -u))
all_pkgs=()
not_in_pkgs=()
while IFS= read -r line; do
  all_pkgs+=("$line")
done <<< "$pkgs"

for item1 in "${sorted_all_depends[@]}"; do
  found=0
  for item2 in "${all_pkgs[@]}"; do
    if [ "$item1" = "$item2" ]; then
      found=1
      break
    fi
  done

  if [ "$found" -eq 0 ]; then
    not_in_pkgs+=("$item1")
  fi
done

echo "------------------额外依赖包不在添加的aur包中，请添加到上面列表中--------------------"
for item in "${not_in_pkgs[@]}"; do
  echo "$item"
done

echo -e "\n-----------克隆失败-------------\n"
for item in "${failed[@]}"; do
    echo $item
done

echo -e "\n-----------空仓库:-------------\n"
for item in "${not_in_aur[@]}"; do
    echo $item
done

