#!/usr/bin/env bash
# find special text content on current directory.
# https://github.com/junegunn/fzf/blob/master/ADVANCED.md
# https://github.com/junegunn/fzf/issues/2323 \

# Switch between Ripgrep launcher mode (CTRL-R) and fzf filtering mode (CTRL-F)
LANG=en_US.UTF-8
rm -f /tmp/rg-fzf-{r,f}
RG_PREFIX="rg --column --line-number --no-heading --color=always --smart-case -g '!{**/node_modules/*,**/.git/*}' --colors 'match:fg:0x66,0xBB,0x6A' --colors 'path:fg:0xF4,0x8F,0xB1' --colors 'column:fg:0x26,0xC6,0xDA'"
INITIAL_QUERY="${*:-}"
: | fzf --ansi --disabled --query "$INITIAL_QUERY" \
	--bind "start:reload($RG_PREFIX {q})+unbind(ctrl-r)" \
	--bind "change:reload:sleep 0.1; $RG_PREFIX {q} || true" \
	--bind "ctrl-f:unbind(change,ctrl-f)+change-prompt(2. fzf> )+enable-search+rebind(ctrl-r)+transform-query(echo {q} > /tmp/rg-fzf-r; cat /tmp/rg-fzf-f)" \
	--bind "ctrl-r:unbind(ctrl-r)+change-prompt(1. ripgrep> )+disable-search+reload($RG_PREFIX {q} || true)+rebind(change,ctrl-f)+transform-query(echo {q} > /tmp/rg-fzf-f; cat /tmp/rg-fzf-r)" \
    --bind 'ctrl-y:execute-silent(echo {4..} | wl-copy)' \
    --bind 'ctrl-p:execute-silent(echo {1} | wl-copy)' \
	--color "hl:-1:underline,hl+:-1:underline:reverse" \
	--prompt '1. ripgrep> ' \
	--delimiter : \
    --header '╱ CTRL-R (ripgrep mode) ╱ CTRL-F (fzf mode) ╱ CTRL-Y (copy content) ╱ CTRL-P (copy filename)' \
	--preview 'bat --color=always {1} --highlight-line {2} --wrap=character --style=numbers' \
	--preview-window 'up,60%,wrap,+{2}+3/3' \
	--bind 'enter:become(vim {1} +{2})'
